/**
 * The guided item catalog. Backed by the Season 1/2 gear inventory
 * (`season1-gear.json`, `season2-gear.json`) generated by
 * scripts/build-season-gear.ts.
 *
 * This replaced the Raidbots `catalog.json` snapshot, now deleted. The season
 * files were adopted only after being checked against it: all 450 previously
 * tracked items were present plus 617 more, all 9,956 shared upgrade rungs
 * agreed with zero conflicts, and sampled rungs matched simc exactly. They also
 * carry slot, armour class, tier set, unique-equipped and source-encounter data
 * the old snapshot lacked. The snapshot survives on the `stable` branch.
 *
 * One consequence: an advanced exact import of an item outside this season's
 * inventory shows `Item <id>` rather than its name, since nothing bundled
 * carries names for older content.
 */
import { createRequire } from 'node:module'
import { combinedIdentity } from './manifest.ts'
import { canEquip, lookupItem } from './itemTable.ts'
import { assertGemCategoryLimits, enchantSlot, findEmbellishment, findEnchant, findGem, socketCount } from './db2.ts'

export interface CatalogVariant {
  track: string; ilvl: number; rank: number; max: number; bonusId: number
  /** Replaces the `rank/max` text for a variant that is not a rung on its track. */
  label?: string
}
export interface CatalogItem {
  id: number; name: string; icon: string; classes?: number[]; bonusIds: number[]
  variants: CatalogVariant[]; source?: string
  /** The item's own secondary stats, biggest first; a converted piece keeps its source's instead. */
  stats?: string
  /** The slot a simc item line is emitted under, e.g. `finger1`. */
  slot: string
  season?: number
  sourceType?: string
}
export interface CatalogSelection {
  /**
   * Optional so stored History payloads, written before crafted selections
   * existed, still deserialize as track selections.
   */
  kind?: 'track'
  itemId: number; track: string; ilvl: number; catalogGenerated?: string
  /** Season 2 class tier identity, with source stats retained by simc redirection. */
  catalyst?: boolean
  /**
   * Legacy guided crafting fields retained so old History payloads deserialize
   * and receive an explicit unsupported-selection error instead of being
   * silently rewritten. Crafted gear has its own configuration type.
   */
  craftedStats?: number[]
  /** Legacy guided craft quality; crafted items use CraftedSelection instead. */
  craftingQuality?: number
  /**
   * Legacy guided embellishment field. Known and unknown ids are rejected for
   * track drops; retained only to surface old History choices for review.
   */
  embellishmentBonusId?: number
  /** Gems, one per available socket, emitted as `gem_id`. */
  gemIds?: number[]
  /** Enchant id, emitted as `enchant_id`. */
  enchantId?: number
}

export interface CatalogResult extends CatalogItem {
  reason?: string
  /** Gem slots this item offers, innate plus bonus-granted. */
  sockets: number
  catalystTarget?: { id: number; name: string }
}

/** One entry of a generated season gear file. */
interface SeasonItem {
  id: number; name: string; icon: string
  slot: string
  allowableClasses?: number[]
  bonusIds?: number[]
  uniqueEquipped?: boolean
  source?: { instanceName?: string; instanceType?: string; encounterName?: string; encounterId?: number }
  upgradeTracks: Array<{ bonusId: number; track: string; rank: number; maxRank: number; itemLevel: number }>
  stats?: Array<{ statId: number; allocation: number }>
}
interface SeasonFile { version: number; generated: string; season: string; items: SeasonItem[] }

const require = createRequire(import.meta.url)

/** Registry slot -> the slot a simc item line is emitted under. */
const EMIT_SLOT: Record<string, string> = {
  head: 'head', neck: 'neck', shoulder: 'shoulder', back: 'back', chest: 'chest',
  waist: 'waist', legs: 'legs', feet: 'feet', wrist: 'wrist', hands: 'hands',
  finger: 'finger1', trinket: 'trinket1',
  one_hand: 'main_hand', two_hand: 'main_hand', ranged: 'main_hand',
  main_hand: 'main_hand', off_hand: 'off_hand', shield: 'off_hand', holdable: 'off_hand'
}

function describeSource(item: SeasonItem): string | undefined {
  const source = item.source
  if (!source) return undefined
  // Tier pieces are listed under the catalyst, but they also drop from raid
  // tokens. A token piece carries the stats below; a converted one keeps the
  // stats of whatever it was made from, so saying only "Catalyst" misleads.
  if (source.instanceType === 'catalyst') return 'Tier set · raid token or catalyst'
  if (source.encounterName && source.instanceName) return source.instanceName + ' · ' + source.encounterName
  return source.instanceName
}

/** The item's own secondaries, biggest first, e.g. "Haste / Crit". */
const SECONDARY_NAMES: Record<number, string> = { 32: 'Crit', 36: 'Haste', 40: 'Versatility', 49: 'Mastery' }
function describeStats(item: SeasonItem): string | undefined {
  const split = (item.stats ?? [])
    .filter((s) => SECONDARY_NAMES[s.statId] && s.allocation > 0)
    .sort((a, b) => b.allocation - a.allocation)
    .map((s) => SECONDARY_NAMES[s.statId])
  return split.length ? split.join(' / ') : undefined
}

interface Catalog { version: number; generated: string; season: string; items: CatalogItem[] }
let data: Catalog | undefined
let index: Map<number, CatalogItem> | undefined

/** Upgrade tracks from lowest to highest. */
export const TRACK_ORDER = ['Adventurer', 'Veteran', 'Champion', 'Hero', 'Myth'] as const

/**
 * The highest upgrade track each source can award in Midnight Season 2.
 *
 * The catalog used to offer every track for every source, so a delve cloak
 * could be configured at Myth 6/6 and simulated into a recommendation for gear
 * that cannot exist. Items upgrade within their track with crests, so the cap
 * is the best track a source awards; everything below it stays reachable.
 *
 * Sourced, not remembered: method.gg's Season 2 Great Vault guide gives Raid
 * Mythic at Myth, the Mythic+ vault at Myth 1/6 (318), Tier 8 delves and
 * Nightmare prey at Hero 1/6 (305), and states the World vault row cannot
 * award Myth. Those item levels match the upgrade ladder this catalog ships
 * from Raidbots exactly (Hero 1/6 = 305, Myth 1/6 = 318), so two independent
 * sources agree. The catalyst converts an item at its existing track, so it
 * inherits the cap of whatever it converts.
 *
 * A source missing here gets no variants rather than every track: an unknown
 * reach is not an unlimited one. A test fails if a rebuild introduces one.
 */
export const TRACK_CAP: Readonly<Record<string, (typeof TRACK_ORDER)[number]>> = {
  raid: 'Myth',
  dungeon: 'Myth',
  catalyst: 'Myth',
  'delve-mid2': 'Hero',
  'prey-mid2': 'Hero'
}

/**
 * Fixed-level drops above the Myth 6/6 cap: the last two bosses of the Season 2
 * raid on Mythic drop at item level 344.
 *
 * This is the best gear in the season, and the catalog could not configure it
 * at all — capped at Myth 6/6 (334), a Mythic final-boss item was simulated ten
 * item levels short, understating exactly the upgrade a raider most needs to
 * weigh. It is not a rung: nothing upgrades into it and it does not upgrade.
 *
 * Three independent pieces of evidence, each checked:
 * - method.gg's Season 2 raid guide (citing Wowhead): on Mythic the last two
 *   bosses drop 344.
 * - Raidbots' encounter data marks The Coiled Altar (2883) and Ula'tek (2895)
 *   with itemSequenceLevel 4, the highest in The Venomous Abyss and the last
 *   two in fight order.
 * - simc resolves bonus 13848 to item level 344 on these items, winning over
 *   the Myth 6/6 bonus; `npm run check:catalog` re-measures it.
 */
export const MYTHIC_FINAL_BOSS = {
  encounterIds: [2883, 2895] as readonly number[],
  ilvl: 344,
  bonusId: 13848,
  label: 'Mythic final boss'
} as const

/** Whether a source can award this track, with unknown sources treated as unable. */
export function trackReachable(sourceType: string | undefined, track: string): boolean {
  const cap = sourceType ? TRACK_CAP[sourceType] : undefined
  if (!cap) return false
  const index = TRACK_ORDER.indexOf(track as (typeof TRACK_ORDER)[number])
  return index >= 0 && index <= TRACK_ORDER.indexOf(cap)
}

/**
 * PvP gear is left out of guided search. Its item level differs inside and
 * outside PvP combat, SimItBoi only simulates Patchwerk, and the catalog carries
 * no upgrade track for it — so every one of these results could be found and
 * then never added. Advanced exact import still accepts them.
 */
export function isPvpSource(sourceType: string | undefined): boolean {
  return sourceType?.startsWith('pvp-') ?? false
}

/**
 * Season 2 first, then Season 1. An item in both keeps its Season 2 entry,
 * which is the one carrying upgrade tracks.
 */
export function catalog(): Catalog {
  if (data) return data
  const current = require('./season2-gear.json') as SeasonFile
  const previous = require('./season1-gear.json') as SeasonFile
  const merged = new Map<number, CatalogItem>()
  for (const file of [current, previous]) {
    for (const item of file.items) {
      if (merged.has(item.id)) continue
      const slot = EMIT_SLOT[item.slot]
      if (!slot) continue
      merged.set(item.id, {
        id: item.id,
        name: item.name,
        icon: item.icon,
        slot,
        season: file === current ? 2 : 1,
        sourceType: item.source?.instanceType,
        ...(item.allowableClasses?.length ? { classes: item.allowableClasses } : {}),
        bonusIds: item.bonusIds ?? [],
        // Capped here so the picker, search and the main-process resolver all
        // see the same reachable set: resolveCatalog refuses any variant that is
        // not in this list.
        variants: [
          ...item.upgradeTracks
            .filter((t) => trackReachable(item.source?.instanceType, t.track))
            .map((t) => ({
              track: t.track, ilvl: t.itemLevel, rank: t.rank, max: t.maxRank, bonusId: t.bonusId
            })),
          // Only a Season 2 raid item from one of the two final encounters, and only
          // one that already reaches Myth: the drop is a Mythic-difficulty reward.
          ...(file === current && item.source?.instanceType === 'raid' &&
            MYTHIC_FINAL_BOSS.encounterIds.includes(item.source.encounterId ?? -1) &&
            item.upgradeTracks.some((t) => t.track === 'Myth')
            ? [{
                track: 'Myth', ilvl: MYTHIC_FINAL_BOSS.ilvl, rank: 6, max: 6,
                bonusId: MYTHIC_FINAL_BOSS.bonusId, label: MYTHIC_FINAL_BOSS.label
              }]
            : [])
        ],
        ...(describeSource(item) ? { source: describeSource(item) } : {}),
        ...(describeStats(item) ? { stats: describeStats(item) } : {})
      })
    }
  }
  data = {
    version: current.version,
    generated: current.generated,
    season: current.season,
    items: [...merged.values()]
  }
  return data
}

/**
 * Content identity of the guided catalog. Replaces the generation timestamp that
 * used to serve this purpose: an identical rebuild produced a new timestamp and
 * invalidated every saved scenario.
 */
export function catalogIdentity(): string {
  return combinedIdentity(['season1-gear.json', 'season2-gear.json'])
}

/** Crit, haste, versatility, mastery: the stats a catalyst conversion carries over. */
const SECONDARY_STATS = new Set([32, 36, 40, 49])

/** Each secondary's share of the item's secondary budget, keyed by stat id. */
function secondaryShares(values: ReadonlyArray<{ statId: number; amount: number }>): Map<number, number> {
  const secondaries = values.filter((v) => SECONDARY_STATS.has(v.statId) && v.amount > 0)
  const total = secondaries.reduce((sum, v) => sum + v.amount, 0)
  return new Map(secondaries.map((v) => [v.statId, total > 0 ? v.amount / total : 0]))
}

/** How far apart two splits are, or Infinity when they use different stats. */
function shareDistance(a: Map<number, number>, b: Map<number, number>): number {
  if (a.size === 0 || a.size !== b.size || [...a.keys()].some((id) => !b.has(id))) return Infinity
  return Math.max(...[...a].map(([id, share]) => Math.abs(share - b.get(id)!)))
}

/**
 * The item whose secondary stats a catalyst-converted tier piece carries.
 *
 * A converted piece keeps the stat split of the item it was made from, which
 * the addon exports as `redirected_base_stats` and the Blizzard API does not.
 * The API does report the resulting ratings, so this finds a season item for
 * the same slot with that split. Any such item gives simc the same stats.
 *
 * Undefined when the piece's own split already matches (it was not converted),
 * when the piece is not in the season data, or when nothing matches closely
 * enough to be sure.
 */
export function statDonor(itemId: number, slot: string, observed: ReadonlyArray<{ statId: number; amount: number }>): number | undefined {
  const wanted = secondaryShares(observed)
  if (wanted.size === 0) return undefined
  const files = [require('./season2-gear.json') as SeasonFile, require('./season1-gear.json') as SeasonFile]
  const shares = (item: SeasonItem): Map<number, number> =>
    secondaryShares((item.stats ?? []).map((s) => ({ statId: s.statId, amount: s.allocation })))
  // Ratings are rounded, so a match is a split within two percentage points.
  const TOLERANCE = 0.02
  // Only a known season item can be told apart from its conversion; anything
  // else is left as it is rather than matched to a stranger by coincidence.
  const own = files.flatMap((f) => f.items).find((i) => i.id === itemId)
  if (!own || shareDistance(wanted, shares(own)) <= TOLERANCE) return undefined
  // simc takes every base stat from the donor, primary included, so the donor
  // must share the piece's primary stat (Agility/Intellect, Strength/Intellect…).
  const primary = (item: SeasonItem): string =>
    (item.stats ?? []).map((s) => s.statId).filter((id) => !SECONDARY_STATS.has(id) && id !== 7).sort().join('/')
  let best: { id: number; distance: number } | undefined
  for (const item of files.flatMap((f) => f.items)) {
    if (item.id === itemId || EMIT_SLOT[item.slot] !== slot || primary(item) !== primary(own)) continue
    const distance = shareDistance(wanted, shares(item))
    if (distance <= TOLERANCE && (!best || distance < best.distance)) best = { id: item.id, distance }
  }
  return best?.id
}

export function catalogItem(id: number): CatalogItem | undefined {
  index ??= new Map(catalog().items.map((i) => [i.id, i]))
  return index.get(id)
}

const slots: Record<string, string> = { HEAD: 'head', NECK: 'neck', SHOULDER: 'shoulder', CLOAK: 'back', CHEST: 'chest', ROBE: 'chest', WRIST: 'wrist', HAND: 'hands', WAIST: 'waist', LEGS: 'legs', FEET: 'feet', FINGER: 'finger1', TRINKET: 'trinket1', WEAPON: 'main_hand', WEAPONMAINHAND: 'main_hand', TWOHWEAPON: 'main_hand', RANGED: 'main_hand', RANGEDRIGHT: 'main_hand', WEAPONOFFHAND: 'off_hand', SHIELD: 'off_hand', HOLDABLE: 'off_hand' }
const classes: Record<string, number> = { warrior: 1, paladin: 2, hunter: 3, rogue: 4, priest: 5, deathknight: 6, shaman: 7, mage: 8, warlock: 9, monk: 10, druid: 11, demonhunter: 12, evoker: 13 }

/**
 * The season inventory first, then the bundled item table, which covers every
 * item id rather than only this season's. Advanced imports of items outside the
 * inventory rely on that fallback for their wrong-slot check.
 */
export function catalogSlot(id: number): string | undefined {
  return catalogItem(id)?.slot ?? slots[lookupItem(id)?.inventoryType ?? '']
}

function compatible(item: CatalogItem, className: string): boolean {
  return canEquip(className, item.id) && (!item.classes || item.classes.includes(classes[className]))
}

/** Only the five bonus-bearing slots; target class and season are resolved here, never supplied by UI. */
export function catalystTarget(item: CatalogItem, className: string): CatalogItem | undefined {
  if (item.season !== 2 || !item.variants.length || !compatible(item, className) ||
    !['head', 'shoulder', 'chest', 'hands', 'legs'].includes(item.slot) || lookupItem(item.id)?.setId) return undefined
  const targets = catalog().items.filter(target => target.season === 2 && target.slot === item.slot &&
    target.sourceType === 'catalyst' && target.classes?.includes(classes[className]) && lookupItem(target.id)?.setId)
  return targets.length === 1 ? targets[0] : undefined
}

export function searchCatalog(query: string, className: string, slot = ''): { items: CatalogResult[]; total: number; season: string; generated: string } {
  if (typeof query !== 'string' || query.length > 120 || typeof slot !== 'string') throw new Error('Invalid item search')
  const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean)
  const matches = catalog().items.filter((i) => {
    const itemSlot = i.slot.replace(/[12]$/, '')
    return !isPvpSource(i.sourceType) && (!slot || itemSlot === slot) && compatible(i, className) && words.every((w) => `${i.name.toLowerCase()} ${i.id}`.includes(w))
  }).sort((a, b) => Number(b.variants.length > 0) - Number(a.variants.length > 0) || a.name.localeCompare(b.name))
  return {
    items: matches.slice(0, 60).map((i) => {
      const tier = catalystTarget(i, className)
      return {
        ...i,
        ...(tier ? { catalystTarget: { id: tier.id, name: tier.name } } : {}),
        sockets: socketCount(i.id, [...i.bonusIds, ...i.variants.map((v) => v.bonusId)]),
        reason: i.variants.length ? undefined : 'No supported upgrade track this season. Use advanced import for an exact variant.'
      }
    }),
    total: matches.length, season: catalog().season, generated: catalogIdentity()
  }
}

/** Resolve again in the main process at run time; never trust renderer tokens or labels. */
export function resolveCatalog(selection: CatalogSelection, className: string): { itemString: string; label: string; ilvl: number } {
  if (!selection || !Number.isInteger(selection.itemId) || !Number.isInteger(selection.ilvl)) throw new Error('Invalid item selection')
  if (selection.catalogGenerated && selection.catalogGenerated !== catalogIdentity()) throw new Error('This selection uses an older item catalog. Search and add the item again to review its current variants.')
  const item = catalogItem(selection.itemId)
  if (!item || !compatible(item, className)) throw new Error('Item is unavailable for this character')
  const slot = item.slot
  const variant = item.variants.find((v) => v.track === selection.track && v.ilvl === selection.ilvl)
  if (!variant) throw new Error('This item, track and item level combination is unavailable')
  if (selection.catalyst !== undefined && typeof selection.catalyst !== 'boolean') throw new Error('Invalid catalyst selection')
  const tier = selection.catalyst ? catalystTarget(item, className) : undefined
  if (selection.catalyst && !tier) throw new Error('This item cannot be converted to a Season 2 tier piece for this character')
  const bonuses = [...new Set([...item.bonusIds, ...(tier?.bonusIds ?? []), variant.bonusId])]

  // Track drops are verified raid/dungeon/catalyst rewards, not crafting
  // recipes. Crafted gear has its own configuration type, so fail closed.
  const stats = selection.craftedStats ?? []
  if (stats.length > 0 || selection.craftingQuality !== undefined) {
    throw new Error('Crafted configurations belong to the Crafted picker, not an upgrade-track drop.')
  }

  // Embellishment, gems and enchant — all validated against the generated DB2
  // table rather than trusted from the renderer.
  const extras: string[] = []
  if (tier) extras.push(`redirected_base_stats=${item.id}`)
  if (selection.embellishmentBonusId !== undefined) {
    const embellishment = findEmbellishment(selection.embellishmentBonusId)
    if (!embellishment) throw new Error('Unknown embellishment')
    throw new Error('Embellishments belong to the Crafted picker, not an upgrade-track drop.')
  }

  const gemIds = selection.gemIds ?? []
  if (gemIds.length > 0) {
    const sockets = socketCount(item.id, bonuses)
    if (gemIds.length > sockets) {
      throw new Error(sockets === 0 ? 'This item has no sockets' : `This item has ${sockets} socket${sockets === 1 ? '' : 's'}`)
    }
    if (gemIds.some((id) => !findGem(id))) throw new Error('Unknown gem')
    assertGemCategoryLimits(gemIds)
    extras.push(`gem_id=${gemIds.join('/')}`)
  }

  if (selection.enchantId !== undefined) {
    const found = findEnchant(selection.enchantId)
    if (!found) throw new Error('Unknown enchant')
    if (found.enchant.slot === null) throw new Error('This enchant has unknown slot eligibility and is unavailable in the guided picker')
    if (found.enchant.slot !== enchantSlot(slot)) throw new Error('This enchant cannot be applied to this item slot')
    extras.push(`enchant_id=${selection.enchantId}`)
  }

  const parts = [`${slot}=,id=${tier?.id ?? item.id}`, `bonus_id=${bonuses.join('/')}`, ...extras]
  return {
    itemString: parts.join(','),
    label: `${tier ? `${tier.name} · Catalyst from ${item.name}` : item.name} · ${variant.label ?? `${variant.track} ${variant.rank}/${variant.max}`}`,
    ilvl: variant.ilvl
  }
}
