/**
 * Lookup over the generated DB2 table.
 *
 * Generated by scripts/build-db2.ts. The table ships with the app; wago.tools is
 * never contacted at runtime, the same arrangement as the Blizzard item table.
 */
import { createRequire } from 'node:module'

const require_ = createRequire(import.meta.url)

export interface Embellishment {
  /** The bonus id that carries the effect. */
  bonusId: number
  spellId: number
  name: string
  /** Icon pack name, or null when the game publishes none for it. */
  icon: string | null
  /**
   * The crafting category this embellishment belongs to. An exact join, and the
   * thing to key eligibility on.
   */
  categoryId: number | null
  category: string | null
  /** The game's own wording of the restriction, kept verbatim as evidence. */
  categoryNote: string | null
  /**
   * What the embellishment may go on, classified from `categoryNote`.
   * PROVISIONAL: derived from prose, not from a structural join — the
   * category → equipment-slot mapping is not established by any table.
   * Treat it as a starting point for verification, never as a legality ruling.
   */
  appliesTo: string
  /** Content scope, so current-expansion embellishments can be told apart. */
  expansion: string
  reagentItemId: number | null
}

/** One crafting quality of a gem or enchant. Tier 0 means it has no tiers. */
export interface QualityTier {
  id: number
  tier: number
  icon: string | null
}

export interface Gem {
  name: string
  /** Item quality (2 uncommon, 4 epic …), distinct from the crafting tier. */
  quality: number
  socketType: number
  /** Stats named, not numbered — the real values come from the probe. */
  effect: string
  /** Crafting qualities of this gem, ascending. Two ids usually share a name. */
  tiers: QualityTier[]
}

export interface Enchant {
  name: string
  /**
   * Classified from the enchant's name, NOT derived from game data, and null
   * wherever the name carries no slot word. The authoritative route
   * covers 982 of 629,333 SpellEffect rows and misses current profession
   * enchants, so this is provisional and deliberately marked as such.
   */
  slot: string | null
  /** Quality tiers of one enchant, ascending. */
  tiers: QualityTier[]
}

/** An item that has a crafting recipe. */
export interface CraftedItem {
  itemId: number
  name: string
  slot: string
  recipeSpellId: number
  /**
   * The reagent slot deciding which embellishments the recipe accepts, or null
   * when the recipe takes none. Its equipment-slot coverage is measured in
   * `embellishmentSlotSets`.
   */
  embellishmentSlotId: number | null
}

interface Db2File {
  version: number
  generated: string
  build: string
  embellishedMarkerBonusId: number
  embellishedLimit: number
  embellishments: Embellishment[]
  limitCategories: Record<string, { name: string; quantity: number }>
  socketBonusIds: Record<string, { count: number; socketType: number }>
  innateSockets: Record<string, number[]>
  gems: Gem[]
  enchants: Enchant[]
  /** item id -> ItemLimitCategory id, for current items belonging to one. */
  itemLimitCategory: Record<string, number>
  /** class -> weapon subclass ids it is proficient with, derived from DB2. */
  weaponProficiency: Record<string, number[]>
  /** Classes that may equip a shield. */
  shieldProficiency: string[]
  craftedItems: CraftedItem[]
  /** Reagent slot id -> the equipment slots its recipes actually produce. */
  embellishmentSlotSets: Record<string, string[]>
}

let table: Db2File | null = null

/** Loaded lazily; not every code path needs it. */
export function db2(): Db2File {
  table ??= require_('./db2.json') as Db2File
  return table
}

export function embellishments(): readonly Embellishment[] {
  return db2().embellishments
}

export function gems(): readonly Gem[] {
  return db2().gems
}

export function enchants(): readonly Enchant[] {
  return db2().enchants
}

/** Enchants whose name claims this slot. Empty is a real answer. */
export function enchantsForSlot(slot: string): readonly Enchant[] {
  const wanted = enchantSlot(slot)
  return db2().enchants.filter((e) => e.slot === wanted)
}

/** Normalize a simc equipment slot to the provisional enchant classification. */
export function enchantSlot(slot: string): string {
  const base = slot.replace(/[12]$/, '')
  return base === 'main_hand' || base === 'off_hand' ? 'weapon' : base
}

/**
 * How many gems an item can take. Two sources and both are required: the item's
 * own sockets, plus any granted by a bonus id. Fixture #1's neck has zero innate
 * sockets and still carries a gem, so innate data alone under-reports.
 */
export function socketCount(itemId: number, bonusIds: readonly number[]): number {
  const data = db2()
  const innate = data.innateSockets[String(itemId)]?.length ?? 0
  let granted = 0
  for (const id of bonusIds) granted += data.socketBonusIds[String(id)]?.count ?? 0
  return innate + granted
}

/** The bonus id an item carries iff it is embellished. */
export function embellishedMarker(): number {
  return db2().embellishedMarkerBonusId
}

/** The game's own cap, from ItemLimitCategory rather than a constant. */
export function embellishmentLimit(): number {
  return db2().embellishedLimit
}

/**
 * Whether an item string's bonus ids mark it embellished. This is a direct
 * reading of game data, not the crafted-epic proxy it replaces.
 */
export function isEmbellishedByBonus(bonusIds: readonly number[]): boolean {
  const marker = embellishedMarker()
  return bonusIds.includes(marker)
}

/** An ItemLimitCategory: how many items of this kind may be worn at once. */
export interface LimitCategory { id: number; name: string; quantity: number }

/** The limit category an item belongs to, if any. */
export function limitCategoryFor(itemId: number): LimitCategory | undefined {
  const data = db2()
  const id = data.itemLimitCategory[String(itemId)]
  if (id === undefined) return undefined
  const category = data.limitCategories[String(id)]
  if (!category) return undefined
  return { id, name: category.name, quantity: category.quantity }
}

/**
 * Rejects gems that would breach a category limit within one item. A quantity-1
 * gem socketed twice resolved happily before this: the category names shipped
 * but membership did not, so nothing could be checked.
 */
export function assertGemCategoryLimits(gemIds: readonly number[]): void {
  const used = new Map<number, number>()
  for (const gemId of gemIds) {
    const category = limitCategoryFor(gemId)
    if (!category) continue
    const count = (used.get(category.id) ?? 0) + 1
    if (count > category.quantity) {
      throw new Error(
        `Only ${category.quantity} ${category.name} can be equipped` +
        (category.quantity === 1 ? ' at a time' : '')
      )
    }
    used.set(category.id, count)
  }
}

/** Item class ids from the bundled table. */
const CLASS_WEAPON = 2
const CLASS_ARMOR = 4
const SUBCLASS_SHIELD = 6

/**
 * Whether a class may wield this weapon, from real proficiency rather than from
 * the spec's configuration list. A spec rule says whether a two-hander is
 * allowed; only this says which kind, so a shadow priest gets a staff and not a
 * two-handed sword.
 *
 * Returns undefined when the class is unknown, which callers must treat as
 * ineligible rather than as permission.
 */
export function canWieldWeapon(className: string, itemClassId: number, itemSubclassId: number): boolean | undefined {
  const data = db2()
  if (itemClassId === CLASS_ARMOR && itemSubclassId === SUBCLASS_SHIELD) {
    return data.shieldProficiency.includes(className)
  }
  if (itemClassId !== CLASS_WEAPON) return true
  const allowed = data.weaponProficiency[className]
  if (!allowed) return undefined
  return allowed.includes(itemSubclassId)
}

export function findEmbellishment(bonusId: number): Embellishment | undefined {
  return db2().embellishments.find((e) => e.bonusId === bonusId)
}

/** Items with a recipe, current content only. */
export function craftedItems(): readonly CraftedItem[] {
  return db2().craftedItems
}

export function findCraftedItem(itemId: number): CraftedItem | undefined {
  return db2().craftedItems.find((c) => c.itemId === itemId)
}

/**
 * Which reagent slot each embellishment restriction class corresponds to. The
 * class is read from the category's prose; the slot
 * coverage it maps to is measured from real recipes, so the *slots* are data
 * even though the *class* is not. Anything unmapped yields no slots, which fails
 * closed rather than allowing everything.
 */
const REAGENT_SLOT_BY_CLASS: Record<string, readonly string[]> = {
  accessories: ['389'],
  weapons_offhands: ['390'],
  weapons: ['390'],
  guns: ['501'],
  armor: ['391', '499', '502'],
  leather_mail: ['391', '499', '502'],
  armor_accessories: ['391', '499', '502', '389'],
  equipment: ['390', '391', '499', '501', '502'],
  weapons_armor: ['390', '391', '499', '501', '502']
}

/**
 * Reagent slots the registry attributes to Engineering: the Engineering Armor
 * recipes carry 499 or 502 where ordinary armor carries 391, and the gun
 * carries 501. Measured from `dawncrest-crafts.json`, not asserted.
 */
const ENGINEERING_REAGENT_SLOTS = ['499', '501', '502']

/**
 * Professions the category prose names. Only Engineering can be tied back to
 * recipes, through the reagent slots above; anything else is named but not
 * attributable, so it resolves to no slots and fails closed.
 */
const PROFESSION = /engineering|blacksmithing|leatherworking|tailoring|jewelcrafting|inscription|alchemy/i

/**
 * The reagent slots an embellishment may occupy. This is the game's own
 * mechanism — an embellishment is a reagent placed in a recipe's embellishment
 * slot — so it is the precise thing to check a recipe against.
 *
 * The class comes from prose and maps to a slot set; a note that also names a
 * profession narrows it further, because e.g. "Midnight Engineering Crafted
 * Equipment" is not every equipment recipe. Empty means not established.
 */
export function embellishmentReagentSlots(embellishment: Embellishment): readonly string[] {
  const slots = REAGENT_SLOT_BY_CLASS[embellishment.appliesTo] ?? []
  const note = embellishment.categoryNote ?? ''
  const profession = note.match(PROFESSION)?.[0].toLowerCase()
  if (!profession) return slots
  if (profession !== 'engineering') return []
  return slots.filter((slot) => ENGINEERING_REAGENT_SLOTS.includes(slot))
}

/**
 * Equipment slots an embellishment may go on. Empty means "not established" —
 * callers must treat that as ineligible, never as unrestricted.
 *
 * Coarse by construction: it collapses every recipe sharing a reagent slot into
 * one answer, so it cannot express armor class, expansion or profession. Use
 * `craftedEmbellishmentProblem` when a specific recipe is in hand.
 */
export function embellishmentSlots(embellishment: Embellishment): readonly string[] {
  const sets = db2().embellishmentSlotSets
  const slots = new Set<string>()
  for (const id of embellishmentReagentSlots(embellishment)) for (const slot of sets[id] ?? []) slots.add(slot)
  return [...slots].sort()
}

/** Whether an embellishment is eligible for an item in this slot. */
export function embellishmentAllowedOn(embellishment: Embellishment, slot: string): boolean {
  const base = slot.replace(/[12]$/, '')
  return embellishmentSlots(embellishment).includes(base)
}

/** The gem a specific item id belongs to, with the matching tier. */
export function findGem(id: number): { gem: Gem; tier: QualityTier } | undefined {
  for (const gem of db2().gems) {
    const tier = gem.tiers.find((t) => t.id === id)
    if (tier) return { gem, tier }
  }
  return undefined
}

/** The classified enchant and quality tier for one enchant id. */
export function findEnchant(id: number): { enchant: Enchant; tier: QualityTier } | undefined {
  for (const enchant of db2().enchants) {
    const tier = enchant.tiers.find((t) => t.id === id)
    if (tier) return { enchant, tier }
  }
  return undefined
}
