/**
 * Lookup over the generated item metadata table.
 *
 * Generated by scripts/build-item-table.ts. The table ships with the app; the
 * Blizzard credentials that built it are never needed at runtime.
 */
import { createRequire } from 'node:module'
import type { CandidateItem } from '../types.ts'
import type { WeaponInventoryType } from '../topgear/weapons.ts'
import { resolveUniqueRule, type UniqueRule } from './unique.ts'

const require_ = createRequire(import.meta.url)

/** `id -> [inventoryType, itemClassId, itemSubclassId, qualityCode, setId?]` (schema v3) */
type ItemRow = [string, number, number, number, number?]

export type Quality =
  | 'poor' | 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary' | 'artifact' | 'heirloom'

const QUALITY_BY_CODE: Record<number, Quality> = {
  0: 'poor', 1: 'common', 2: 'uncommon', 3: 'rare',
  4: 'epic', 5: 'legendary', 6: 'artifact', 7: 'heirloom'
}

interface TableFile {
  version: number
  generated: string
  namespace: string
  counts: { items: number; sets: number }
  items: Record<string, ItemRow>
  sets: Record<string, { name: string; items: number[] }>
  unique?: Record<string, UniqueRule>
}

let table: TableFile | null = null

/** Loaded lazily — the table is ~2.6 MB and not every code path needs it. */
export function itemTable(): TableFile {
  table ??= require_('./items.json') as TableFile
  return table
}

export type ArmorClass = 'cloth' | 'leather' | 'mail' | 'plate' | 'shield' | 'misc'

/** Blizzard item_class ids. */
const CLASS_ARMOR = 4
const CLASS_WEAPON = 2

/** item_subclass ids within item_class 4 (Armor). */
const ARMOR_SUBCLASS: Record<number, ArmorClass> = {
  0: 'misc',
  1: 'cloth',
  2: 'leather',
  3: 'mail',
  4: 'plate',
  6: 'shield'
}

/** Which armour class each class wears at max level. */
const CLASS_ARMOR_TYPE: Record<string, ArmorClass> = {
  mage: 'cloth', priest: 'cloth', warlock: 'cloth',
  druid: 'leather', rogue: 'leather', monk: 'leather', demonhunter: 'leather',
  hunter: 'mail', shaman: 'mail', evoker: 'mail',
  warrior: 'plate', paladin: 'plate', deathknight: 'plate'
}

const INVENTORY_TO_WEAPON: Record<string, WeaponInventoryType> = {
  TWOHWEAPON: 'two_hand',
  WEAPON: 'one_hand',
  WEAPONMAINHAND: 'main_hand_only',
  WEAPONOFFHAND: 'off_hand_only',
  SHIELD: 'shield',
  HOLDABLE: 'holdable',
  RANGED: 'ranged',
  RANGEDRIGHT: 'ranged'
}

export interface ItemMeta {
  inventoryType: string
  itemClassId: number
  itemSubclassId: number
  quality?: Quality
  setId?: number
  unique?: UniqueRule
  /** Undefined for anything that is not a weapon-slot item. */
  weaponType?: WeaponInventoryType
  /** Undefined for anything that is not armour. */
  armorClass?: ArmorClass
}

export function lookupItem(id: number): ItemMeta | undefined {
  const row = itemTable().items[String(id)]
  if (!row) return undefined
  const [inventoryType, itemClassId, itemSubclassId, qualityCode, setId] = row
  return {
    inventoryType,
    itemClassId,
    itemSubclassId,
    quality: QUALITY_BY_CODE[qualityCode],
    setId,
    unique: itemTable().unique?.[String(id)],
    weaponType: INVENTORY_TO_WEAPON[inventoryType],
    armorClass:
      itemClassId === CLASS_ARMOR ? ARMOR_SUBCLASS[itemSubclassId] : undefined
  }
}

export function lookupCandidate(c: CandidateItem): ItemMeta | undefined {
  return lookupItem(c.item.id)
}

/** The set this item belongs to, if any — used for tier detection. */
export function setOf(id: number): { id: number; name: string; items: number[] } | undefined {
  const meta = lookupItem(id)
  if (meta?.setId === undefined) return undefined
  const s = itemTable().sets[String(meta.setId)]
  return s ? { id: meta.setId, ...s } : undefined
}

/**
 * Whether a character of `className` can equip this item.
 *
 * Catches the common case — bags full of other classes' loot — BEFORE simc
 * aborts the whole profileset batch on it. Items of unknown provenance are
 * allowed through rather than silently dropped: the drop-and-retry path in
 * `runDeltaBatch` remains the backstop.
 */
export function canEquip(className: string, id: number): boolean {
  const meta = lookupItem(id)
  if (!meta) return true // unknown to the table — let simc decide
  return isArmorCompatible(className, meta)
}

export function isArmorCompatible(className: string, meta: ItemMeta): boolean {
  // Cloaks can be classified as Cloth by the API but are wearable by every class.
  if (['CLOAK', 'FINGER', 'TRINKET', 'NECK'].includes(meta.inventoryType)) return true
  if (meta.itemClassId !== CLASS_ARMOR) return true // weapons handled by weapon rules
  if (meta.armorClass === undefined) return true
  // Cloaks, rings, necks, trinkets are armour class "misc" and universal.
  if (meta.armorClass === 'misc') return true
  // Shields are gated by spec rules, not armour class.
  if (meta.armorClass === 'shield') return true
  const wears = CLASS_ARMOR_TYPE[className]
  if (!wears) return true
  return meta.armorClass === wears
}

export function isWeaponClass(id: number): boolean {
  return lookupItem(id)?.itemClassId === CLASS_WEAPON
}

export interface TableInfo {
  version: number
  generated: string
  namespace: string
  items: number
  sets: number
}

export function tableInfo(): TableInfo {
  const t = itemTable()
  return {
    version: t.version,
    generated: t.generated,
    namespace: t.namespace,
    items: t.counts.items,
    sets: t.counts.sets
  }
}

export interface TableCoverage extends TableInfo {
  /** Distinct item ids seen in the profile. */
  checked: number
  /** Ids the table has no row for. */
  unknown: number[]
  /** Age of the table in whole days. */
  ageDays: number
  stale: boolean
  reason?: string
}

/**
 * Reports how well the bundled table covers a specific profile.
 *
 * Item ids the table has never heard of are the only *direct* evidence that the
 * table needs regenerating — far better than a date heuristic, because a table
 * generated yesterday can still be missing items added in a hotfix, while a
 * months-old table covering every item the player owns is perfectly serviceable.
 *
 * Unknown items are not an error: `canEquip()` deliberately lets them through
 * for simc to judge. But they mean weapon rules and unique-equipped
 * constraints cannot be enforced for those items, which is exactly the gap that
 * produced a phantom upgrade before this table existed.
 */
export function coverageFor(itemIds: readonly number[]): TableCoverage {
  const info = tableInfo()
  const t = itemTable()
  const distinct = [...new Set(itemIds)]
  const unknown = distinct.filter((id) => !t.items[String(id)])
  const ageDays = Math.max(
    0,
    Math.floor((Date.now() - Date.parse(info.generated)) / 86_400_000)
  )
  return {
    ...info,
    checked: distinct.length,
    unknown,
    ageDays,
    stale: unknown.length > 0,
    reason:
      unknown.length > 0
        ? `${unknown.length} of ${distinct.length} items in this profile are missing from the item table. Weapon and unique-equipped rules cannot be enforced for them. Regenerate with: npm run build:items`
        : undefined
  }
}

/** True when an item string carries a `crafting_quality` token. */
export function isCrafted(item: { tokens: Array<{ key: string }> }): boolean {
  return item.tokens.some((t) => t.key === 'crafting_quality')
}

/**
 * The unique-equipped rule for a specific candidate, combining the API's data
 * with the crafted-epic and ring/trinket domain rules. Crafted detection needs the item *string*,
 * not just the id, which is why this takes a candidate rather than an id.
 */
export function uniqueRuleFor(c: CandidateItem): UniqueRule {
  const meta = lookupItem(c.item.id)
  return resolveUniqueRule(meta?.unique, {
    quality: meta?.quality,
    inventoryType: meta?.inventoryType,
    crafted: isCrafted(c.item)
  })
}
